valgrind check

diff --git a/.github/workflows/memcheck.yaml b/.github/workflows/memcheck.yaml
--- a/.github/workflows/memcheck.yaml
+++ b/.github/workflows/memcheck.yaml
@@ -1,102 +1,37 @@
 # For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
 # https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
-on:
-  push:
-    branches:
-      - main
-      - master
-      - '**valgrind**'
-    paths:
-      - '.github/workflows/memcheck.yml'
-      - 'src/**'
-      - 'inst/include/**'
-      - 'memcheck/**'
-      - 'tests/testthat/**.R'
-      - 'vignettes/**.Rmd'
-  pull_request:
-    branches:
-      - main
-      - master
-    paths:
-      - '.github/workflows/memcheck.yml'
-      - 'src/**'
-      - 'inst/include/**'
-      - 'memcheck/**'
+on: [push, pull_request]
 
-
-name: mem-check
+name: valgrind
 
 jobs:
-  mem-check:
-    runs-on: ubuntu-20.04
+  valgrind-check:
+    # Always run only on master, otherwise only if "[valgrind-check]" appears
+    # in the commit comment. An empty commit can be used as follows:
+    #   git commit --allow-empty -m 'Trigger [valgrind-check]'
+    if: contains(github.event.head_commit.message, '[valgrind-check]') || github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
 
-    name: valgrind ${{ matrix.config.test }}
+    runs-on: ubuntu-latest
 
-    strategy:
-      fail-fast: false
-      matrix:
-        config:
-          - {test: 'tests'}
-          - {test: 'examples'}
-          - {test: 'vignettes'}
-
-    env:
-      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
-      _R_CHECK_FORCE_SUGGESTS_: false
-      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
-      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+    name: valgrind-check
 
     steps:
       - uses: actions/checkout@v2
 
-      - uses: r-lib/actions/setup-r@v1
+      - name: Check with valgrind
+        run: bash inst/tools/valgrind-check.sh
+
+      - name: Detect valgrind issues
+        working-directory: valgrind-check
+        run: |
+          if grep -iv "ERROR SUMMARY: 0 errors" valgrind-summary; then
+            echo "::error ::Found valgrind errors"
+            exit 1
+          fi
+
+      - name: Upload valgrind results
+        if: always()
+        uses: actions/upload-artifact@main
         with:
-          r-version: release # CRAN uses devel, but takes ages to load deps.
-
-      - uses: r-lib/actions/setup-pandoc@master
-
-      - name: Query dependencies
-        run: |
-          install.packages('remotes')
-          saveRDS(remotes::dev_package_deps(dependencies = c('soft', 'Config/Needs/memcheck')), ".github/depends.Rds", version = 2)
-          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
-        shell: Rscript {0}
-
-      - name: Cache R packages
-        uses: actions/cache@v2
-        with:
-          path: ${{ env.R_LIBS_USER }}
-          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
-          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
-
-      - name: Install system dependencies
-        run: |
-          sudo apt-get install valgrind texlive-latex-base
-          while read -r cmd
-          do
-            eval sudo $cmd
-          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
-
-      - name: Install dependencies
-        run: |
-          remotes::install_github('emmanuelparadis/ape')
-          if ("${{ matrix.config.test }}" == 'tests') {
-            remotes::install_github('r-lib/brio#20') # brio mem leak
-          }
-          remotes::install_deps(dependencies = c('soft', 'Config/Needs/memcheck'))
-        shell: Rscript {0}
-
-      - name: Install package
-        run: |
-          cd ..
-          R CMD build --no-manual --no-resave-data TreeTools
-          R CMD INSTALL TreeTools*.tar.gz
-          cd TreeTools
-
-      - name: valgrind - memcheck ${{ matrix.config.test }}
-        run: |
-          R -d "valgrind --tool=memcheck \
-          --leak-check=full \
-          --errors-for-leak-kinds=definite \
-          --error-exitcode=1" \
-          --vanilla < memcheck/${{ matrix.config.test }}.R
+          name: valgrind-results
+          path: valgrind-check
